name = "lofi-so"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2025-04-24"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "eventData"
id = "a582ee811be9420d8bdc1bbeaa437fee"